apiVersion: apps/v1
kind: Deployment
metadata:
  name: owntracks
spec:
  selector:
    matchLabels:
      app: owntracks
  template:
    metadata:
      labels:
        app: owntracks
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: owntracks
          image: ko://main.go
          args:
            [
              "--ts-auth-key",
              "$(TS_AUTH_KEY)",
              "--db-host",
              "$(DB_HOST)",
              "--db-user",
              "$(DB_USER)",
              "--db-password",
              "$(DB_PWD)",
              "--db-name",
              "$(DB_NAME)",
            ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: ts-auth-key
                  key: key
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: owntracks-app
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: owntracks-app
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: owntracks-app
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: owntracks-app
                  key: dbname
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: owntracks
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 1Gi
    storageClass: local-path
---
apiVersion: v1
kind: Secret
metadata:
  name: ts-auth-key
type: Opaque
data:
  key: "your-key"
