version: 3

tasks:
  run:
    cmds:
      - go run main.go {{.CLI_ARGS}}
  build:
    cmds:
      - go build -o bin/owntracks-api
      - ko build main.go
  deploy:
    cmds:
      - ko apply -f deploy/deployment.yaml
