apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-iscsi-delete
